# Generated by Django 5.1.3 on 2024-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0005_servicerequest_email_servicerequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
